"""Generate the launcher-managed conda helper files (mod_v2 §7, §9, §13).

Three files are produced and bound read-only into the sandbox:

* ``/sandbox/bin/conda`` — the controlled conda shim. It is a **self-contained**
  Python script: the entire :mod:`kimi_sandbox.conda_policy` source is inlined
  so the shim depends on nothing but the standard library and runs with an empty
  ``PYTHONPATH`` (mod_v2 §7.2). ``conda_policy`` already ends with a
  ``__main__`` guard calling ``shim_main``, so the inlined copy is directly
  runnable.
* ``/sandbox/etc/condarc`` — pins ``envs_dirs``/``pkgs_dirs`` to the writable
  area first, then the read-only host envs (§9).
* ``/sandbox/etc/conda-bash-env`` — sourced via ``BASH_ENV`` so ``conda
  activate`` works in non-interactive ``bash -lc`` (§8); only written when shell
  integration is enabled.

The files are regenerated on every launch (they are launcher-owned, not user
config) and are written under the per-profile state root.
"""

from __future__ import annotations

import os
import tempfile
from pathlib import Path

from . import conda_policy
from .config import (
    SANDBOX_CONDA_BASH_ENV,
    SANDBOX_CONDA_EXISTING_ENVS,
    SANDBOX_CONDA_SHIM,
    SANDBOX_CONDARC,
    GeneratedFileMount,
)
from .paths import ensure_dir

_SHIM_HEADER_BODY = (
    "# Generated by kimi-sandbox; mounted read-only at /sandbox/bin/conda.\n"
    "# Self-contained: the kimi_sandbox.conda_policy source is inlined verbatim\n"
    "# so this shim runs inside the sandbox with no PYTHONPATH (mod_v2 §7.2).\n"
    "# Do not edit; regenerated on every launch.\n"
)


def conda_generated_dir(state_root: Path, profile: str) -> Path:
    """Return the per-profile directory holding the generated conda files."""
    return state_root / "generated" / profile / "conda"


def render_conda_shim(original_root: str) -> str:
    """Return the full source of the self-contained conda shim (audit #10).

    The shebang points at the conda root's own interpreter
    (``<original_root>/bin/python``) rather than ``/usr/bin/env python3`` so the
    shim does not depend on a system Python being present inside the sandbox —
    the conda root (which always ships a python) is guaranteed to be mounted.

    Note (audit #5): this shim is a convenience + early-rejection layer, *not*
    the security boundary. The real conda binary remains directly reachable
    inside the sandbox; the guarantees that host envs stay intact come from the
    read-only bind mounts plus the launcher-forced CONDA_ENVS_PATH/CONDA_PKGS_DIRS
    (which steer all writes into the sandbox-writable area), and hold even if
    this shim is bypassed entirely.
    """
    shebang = f"#!{original_root.rstrip('/')}/bin/python\n"
    policy_src = Path(conda_policy.__file__).read_text(encoding="utf-8")
    return shebang + _SHIM_HEADER_BODY + "\n" + policy_src


def render_condarc(writable_root: str, original_root: str) -> str:
    """Render ``/sandbox/etc/condarc`` (§9).

    Writable env/pkg dirs come first so new envs land in the sandbox area; the
    read-only host envs follow (via the original-prefix path for shebang compat).
    The read-only root package cache is deliberately *not* listed (§7.3).
    """
    writable = writable_root.rstrip("/")
    original = original_root.rstrip("/")
    return (
        "# generated by kimi-sandbox; mounted read-only\n"
        "envs_dirs:\n"
        f"  - {writable}/envs\n"
        f"  - {original}/envs\n"
        f"  - {SANDBOX_CONDA_EXISTING_ENVS}\n"
        "pkgs_dirs:\n"
        f"  - {writable}/pkgs\n"
        "auto_activate_base: false\n"
        "always_copy: true\n"
    )


def render_conda_bash_env() -> str:
    """Render the ``BASH_ENV`` hook enabling ``conda activate`` (§8).

    CONDARC / CONDA_ENVS_PATH / CONDA_PKGS_DIRS are already injected into the
    sandbox environment by the launcher (single source of truth, audit #3), so
    this hook does *not* re-declare them — it only loads conda's bash
    integration so ``conda activate`` works, then points the conda bash function
    at the controlled shim.

    Pointing ``CONDA_EXE`` at the shim means a ``conda install`` issued *before*
    any ``conda activate`` is routed through the mutation policy (early, clear
    rejection). Note that conda's own ``activate`` re-exports ``CONDA_EXE`` back
    to the real binary, so after an activate the shim is bypassed and the
    read-only bind mount becomes the active guarantee (which is the real
    boundary in all cases — see the README security model).
    """
    return (
        "# generated by kimi-sandbox; mounted read-only\n"
        'if [ -x "${KIMI_SANDBOX_CONDA_ORIGINAL_ROOT}/bin/conda" ]; then\n'
        '  __kimi_conda_setup="$("${KIMI_SANDBOX_CONDA_ORIGINAL_ROOT}/bin/conda" '
        "'shell.bash' 'hook' 2>/dev/null)\" || __kimi_conda_setup=\"\"\n"
        '  if [ -n "$__kimi_conda_setup" ]; then\n'
        '    eval "$__kimi_conda_setup"\n'
        '  elif [ -f "${KIMI_SANDBOX_CONDA_ORIGINAL_ROOT}/etc/profile.d/conda.sh" ]; '
        "then\n"
        '    . "${KIMI_SANDBOX_CONDA_ORIGINAL_ROOT}/etc/profile.d/conda.sh"\n'
        "  fi\n"
        "  unset __kimi_conda_setup\n"
        "fi\n"
        "\n"
        "# Route the conda bash function through the controlled shim so a\n"
        "# 'conda install' issued before any 'conda activate' is policed early.\n"
        "# (conda's own activate re-exports CONDA_EXE to the real binary, after\n"
        "# which the read-only bind mount is the guarantee -- it always is.)\n"
        f'export CONDA_EXE="{SANDBOX_CONDA_SHIM}"\n'
    )


def _atomic_write(path: Path, content: str, mode: int) -> None:
    """Write ``content`` to ``path`` atomically with ``mode`` (audit #11).

    Writes to a temp file in the same directory, fsync-free chmod, then
    ``os.replace`` so a concurrent launch of the same profile never observes a
    half-written shim/condarc (the rename is atomic on the same filesystem).
    """
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=f".{path.name}.")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.chmod(tmp, mode)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def prepare_conda_generated_files(
    *,
    state_root: Path,
    profile: str,
    writable_root: str,
    original_root: str,
    shell_integration: bool,
) -> tuple[GeneratedFileMount, ...]:
    """Write the generated conda files and return their read-only mounts.

    The shim is written ``0755`` (executable); condarc and the bash hook are
    ``0644``. Each file is written atomically (temp + rename, audit #11) and
    overwritten on each launch. Returns a tuple of :class:`GeneratedFileMount`
    for the bwrap builder to bind read-only.
    """
    gen_dir = conda_generated_dir(state_root, profile)
    ensure_dir(gen_dir)

    shim_path = gen_dir / "conda"
    _atomic_write(shim_path, render_conda_shim(original_root), 0o755)

    condarc_path = gen_dir / "condarc"
    _atomic_write(condarc_path, render_condarc(writable_root, original_root), 0o644)

    mounts = [
        GeneratedFileMount(
            source=shim_path, target=SANDBOX_CONDA_SHIM, executable=True
        ),
        GeneratedFileMount(source=condarc_path, target=SANDBOX_CONDARC),
    ]

    if shell_integration:
        bash_env_path = gen_dir / "conda-bash-env"
        _atomic_write(bash_env_path, render_conda_bash_env(), 0o644)
        mounts.append(
            GeneratedFileMount(
                source=bash_env_path, target=SANDBOX_CONDA_BASH_ENV
            )
        )

    return tuple(mounts)


__all__ = [
    "conda_generated_dir",
    "render_conda_shim",
    "render_condarc",
    "render_conda_bash_env",
    "prepare_conda_generated_files",
]
